include:
  - proxy.yaml
services:

  web:
    build:
      context: ./                   # путь до докерфайла
      dockerfile: Dockerfile        # имя докерфайла
    container_name: web             # имя контейнера
    ports:                          # проброс портов
      - '5000:5000'                 # номер порта
    restart: always                 # перезапуск контейнера
    env_file: .env                  # файл с переменными
    environment:                    # блок переменных
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_USER=${MYSQL_USER}
      - DB_HOST=db

    networks:
      backend:                      # добавить в сеть backend
        ipv4_address: 172.20.0.5      # статический IPv4
  db:
    image: mysql:8.0   # версия снимка
    container_name: db # имя контейнера
    ports:
      - '3306:3306'
    restart: always
    env_file: .env
    environment:
      # Все параметры описываем в файле .env в папке проекта
      - TZ=Europe/Moscow
      - MYSQL_ROOT_HOST="%"
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}
    networks:
      backend:
        ipv4_address: 172.20.0.10


volumes:
  mysql_data: {}